### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by nchieffo** [raelix/HA-Radoff-integration#1]
It is unclear how to obtain client_id, pool_id and pool_region
Could you please support me?

**Comment by raelix** [comment]
Hello, these parameter comes from your radoff application. Do you know how to get them?

**Comment by nchieffo** [comment]
I can't find them at a glance, can you please send some steps how to obtain them?

**Comment by raelix** [comment]
Well, you should check it in the connection established from your mobile application but I understand it could be a little bit complicated. You may try these:
```
pool_id: eu-west-1_zD4CSIZ6i
pool_region: eu-west-1
client_id: 61ckd0c4qoq0ov7mmphrj7kstj
```
Plz let me know if they work for you

**Comment by nchieffo** [comment]
Yes they work! Thank you very much.
I guess you can add those values to the main readme file

**Comment by raelix** [comment]
> Yes they work! Thank you very much. I guess you can add those values to the main readme file

gr8! I'm glad to hear it! 

@nchieffo If you like the integration plz remember to add a star (if u want) :)
